/**
 * Types for the fertility addon — Seguimientos Automatizados.
 *
 * These complement the generated Supabase types where the autogenerated
 * file is not in sync with migrations 127-131. Once `npm run types` is
 * regenerated against the live DB, prefer the generated types and keep
 * only the derived/utility types here.
 */

export type FollowupStatus =
  | "pendiente"
  | "contactado"
  | "agendado_via_contacto"
  | "agendado_organico_dentro_ventana"
  | "pospuesto"
  | "desistido_silencioso"
  | "vencido"
  | "cerrado_manual";

export type FollowupSource = "manual" | "rule" | "system";

export type FollowupClosureReason =
  | "agendado_via_contacto"
  | "agendado_organico_dentro_ventana"
  | "desistido_silencioso"
  | "vencido"
  | "cerrado_manual";

export type ContactEventType =
  | "auto_email"
  | "auto_whatsapp"
  | "manual_contacted"
  | "manual_whatsapp"
  | "manual_close"
  | "budget_record_created"
  // mig 142 — Phase 5 prep, treatment lifecycle.
  | "rule_transition"
  | "treatment_started"
  | "budget_accepted_pending_start_alert";

export type ContactDeliveryStatus =
  | "sent"
  | "failed"
  | "skipped_no_email"
  | "skipped_no_phone"
  | "skipped_no_whatsapp_config"
  | "skipped_template_not_approved"
  | "skipped_template_missing"
  | "skipped_template_disabled"
  | "unknown";

export interface ContactEvent {
  type: ContactEventType;
  at: string;
  by_user_id?: string | null;
  delivery_status: ContactDeliveryStatus;
  reason?: string;
  channel?: "email" | "whatsapp";
  error?: string;
  budget_record_id?: string;
  /** mig 142 — only populated for `type='rule_transition'` events. */
  from_rule?: string;
  /** mig 142 — only populated for `type='rule_transition'` events. */
  to_rule?: string;
}

export interface FollowupRuleRow {
  id: string;
  organization_id: string | null;
  addon_key: string;
  rule_key: string;
  trigger_event: "appointment_completed" | "treatment_plan_created" | "plan_status_changed";
  trigger_category_key: string | null;
  target_category_key: string | null;
  delay_days: number;
  is_active: boolean;
  is_system: boolean;
  max_attempts: number;
  whatsapp_template_id: string | null;
  email_template_key: string | null;
  created_at: string;
}

export interface MessageTemplateRow {
  id: string;
  organization_id: string | null;
  addon_key: string;
  template_key: string;
  channel: "email" | "whatsapp_meta_ref";
  tone: "amable" | "directo" | "ultimo_recordatorio";
  subject: string | null;
  body: string;
  is_system: boolean;
  created_at: string;
}

export interface CanonicalCategoryRow {
  id: string;
  addon_key: string;
  category_key: string;
  display_name: string;
  description: string | null;
  sort_order: number;
}

export interface FertilityCanonicalMapping {
  category_key: string;
  service_ids: string[];
}

export const FERTILITY_TIER_GROUP = "fertility";
export const FERTILITY_BASIC_KEY = "fertility_basic";
export const FERTILITY_PREMIUM_KEY = "fertility_premium";

export const BUDGET_TREATMENT_TYPES = [
  "FIV",
  "IIU",
  "INDUCCION",
  "CRIO",
  "OVODONACION",
  "ROPA",
  "TED",
  "DUOSTIM",
  "OTRO",
] as const;

export type BudgetTreatmentType = (typeof BUDGET_TREATMENT_TYPES)[number];

export const BUDGET_TREATMENT_TYPE_LABELS: Record<BudgetTreatmentType, string> = {
  FIV: "FIV (Fertilización In Vitro)",
  IIU: "IIU (Inseminación Intrauterina)",
  INDUCCION: "Inducción de ovulación",
  CRIO: "Criopreservación",
  OVODONACION: "Ovodonación",
  ROPA: "Método ROPA",
  TED: "TED (Transferencia Embrionaria Diferida)",
  DUOSTIM: "DUO STIM (Acumulación de Embriones)",
  OTRO: "Otro",
};

/**
 * `services.name` → BudgetTreatmentType. Inferencia ÚNICA para toda la
 * app (mig 180): la usan el assign de presupuestos (lo que se guarda en
 * `budget_records.treatment_type`) y el router de plantillas PDF. Antes
 * existían dos copias divergentes (assign sin TED → guardaba OTRO;
 * generate.tsx con TED) y el PDF podía rutear distinto de lo almacenado.
 *
 * Orden importa: DUOSTIM va antes que TED porque un nombre como
 * "DUO STIM (doble estimulación y transferencia)" contiene
 * "transferencia" y caería en la plantilla equivocada.
 */
export function inferTreatmentTypeFromServiceName(
  serviceName: string | null,
): BudgetTreatmentType {
  if (!serviceName) return "OTRO";
  const n = serviceName.toLowerCase();
  if ((n.includes("duo") && n.includes("stim")) || n.includes("acumulaci"))
    return "DUOSTIM";
  if (n.includes("ovodon")) return "OVODONACION";
  if (n.includes("ropa")) return "ROPA";
  if (n.includes("crio")) return "CRIO";
  if (n.includes("inseminaci") || n.includes("iiu")) return "IIU";
  if (n.includes("transferencia") || n.includes("ted")) return "TED";
  if (n.includes("inducci")) return "INDUCCION";
  if (n.includes("fiv") || n.includes("fecundaci")) return "FIV";
  return "OTRO";
}

export type BudgetAcceptanceStatus =
  | "pending_acceptance"
  | "accepted"
  | "in_progress"
  | "completed"
  | "rejected"
  | "expired";

export interface BudgetRecord {
  id: string;
  organization_id: string;
  patient_id: string;
  treatment_plan_id: string | null;
  sent_by_user_id: string | null;
  /** Nullable since mig 140: \"assigned\" budgets exist before they are sent. */
  sent_at: string | null;
  treatment_type: BudgetTreatmentType;
  amount: number | null;
  notes: string | null;
  acceptance_status: BudgetAcceptanceStatus;
  accepted_at: string | null;
  rejected_at: string | null;
  rejection_reason: string | null;
  followup_id: string | null;
  /** mig 140 — service the tier was assigned from. NULL on legacy rows. */
  service_id: string | null;
  /** mig 140 — A | B | C | NULL for custom one-offs. */
  tier: "A" | "B" | "C" | null;
  /** mig 140 — set by /api/budgets/assign at creation time. */
  assigned_at: string | null;
  /** mig 140 — the doctor (or whoever) that assigned the tier. */
  assigned_by_user_id: string | null;
  /** mig 142 — set by POST /api/budgets/[id]/start when transitioning accepted → in_progress. */
  started_at: string | null;
  /** mig 142 — auth.users.id of the staff member that marked treatment started. */
  started_by_user_id: string | null;
  /** mig 142 — set by POST /api/budgets/[id]/complete (admin/owner only). */
  completed_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface BudgetRecordWithJoins extends BudgetRecord {
  patient?: {
    id: string;
    first_name: string | null;
    last_name: string | null;
    phone: string | null;
  } | null;
  sent_by?: {
    id: string;
    full_name: string | null;
  } | null;
  followup?: {
    id: string;
    expected_by: string | null;
    status: string | null;
  } | null;
}

/** The 3 essential canonical categories that must be mapped for the
 *  Tier 2 rules to fire. UI shows these with a star, but the API only
 *  warns — it never blocks (spec sec. 6.3). */
export const FERTILITY_ESSENTIAL_CATEGORIES = [
  "fertility.first_consultation",
  "fertility.second_consultation",
  "fertility.treatment_decision",
] as const;
