/**
 * Types for the fertility addon — Seguimientos Automatizados.
 *
 * These complement the generated Supabase types where the autogenerated
 * file is not in sync with migrations 127-131. Once `npm run types` is
 * regenerated against the live DB, prefer the generated types and keep
 * only the derived/utility types here.
 */

export type FollowupStatus =
  | "pendiente"
  | "contactado"
  | "agendado_via_contacto"
  | "agendado_organico_dentro_ventana"
  | "pospuesto"
  | "desistido_silencioso"
  | "vencido"
  | "cerrado_manual";

export type FollowupSource = "manual" | "rule" | "system";

export type FollowupClosureReason =
  | "agendado_via_contacto"
  | "agendado_organico_dentro_ventana"
  | "desistido_silencioso"
  | "vencido"
  | "cerrado_manual";

export type ContactEventType =
  | "auto_email"
  | "auto_whatsapp"
  | "manual_contacted"
  | "manual_whatsapp"
  | "manual_close";

export type ContactDeliveryStatus =
  | "sent"
  | "failed"
  | "skipped_no_email"
  | "skipped_no_phone"
  | "skipped_no_whatsapp_config"
  | "skipped_template_not_approved"
  | "skipped_template_missing"
  | "unknown";

export interface ContactEvent {
  type: ContactEventType;
  at: string;
  by_user_id: string | null;
  delivery_status: ContactDeliveryStatus;
  reason?: string;
  channel?: "email" | "whatsapp";
  error?: string;
}

export interface FollowupRuleRow {
  id: string;
  organization_id: string | null;
  addon_key: string;
  rule_key: string;
  trigger_event: "appointment_completed" | "treatment_plan_created" | "plan_status_changed";
  trigger_category_key: string | null;
  target_category_key: string | null;
  delay_days: number;
  is_active: boolean;
  is_system: boolean;
  max_attempts: number;
  whatsapp_template_id: string | null;
  email_template_key: string | null;
  created_at: string;
}

export interface MessageTemplateRow {
  id: string;
  organization_id: string | null;
  addon_key: string;
  template_key: string;
  channel: "email" | "whatsapp_meta_ref";
  tone: "amable" | "directo" | "ultimo_recordatorio";
  subject: string | null;
  body: string;
  is_system: boolean;
  created_at: string;
}

export interface CanonicalCategoryRow {
  id: string;
  addon_key: string;
  category_key: string;
  display_name: string;
  description: string | null;
  sort_order: number;
}

export interface FertilityCanonicalMapping {
  category_key: string;
  service_ids: string[];
}

export const FERTILITY_TIER_GROUP = "fertility";
export const FERTILITY_BASIC_KEY = "fertility_basic";
export const FERTILITY_PREMIUM_KEY = "fertility_premium";

/** The 3 essential canonical categories that must be mapped for the
 *  Tier 2 rules to fire. UI shows these with a star, but the API only
 *  warns — it never blocks (spec sec. 6.3). */
export const FERTILITY_ESSENTIAL_CATEGORIES = [
  "fertility.first_consultation",
  "fertility.second_consultation",
  "fertility.treatment_decision",
] as const;
