"use client";

import { createContext, useContext, useEffect, useState } from "react";

type Language = "es" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Sidebar
    "nav.dashboard": "Dashboard",
    "nav.account": "Cuenta",
    "nav.settings": "Configuración",
    "nav.logout": "Cerrar sesión",
    "nav.logout_success": "Sesión cerrada",
    "nav.scheduler": "Agenda",
    "nav.admin": "Administración",
    "nav.admin_offices": "Consultorios",
    "nav.admin_doctors": "Doctores",
    "nav.admin_services": "Servicios",
    "nav.admin_lookups": "Variables",
    "nav.admin_variables": "Variables Globales",
    "nav.admin_members": "Miembros",
    "nav.founder": "Founder",

    // Account page
    "account.title": "Mi cuenta",
    "account.subtitle": "Administra tu información personal",
    "account.personal_data": "Datos personales",
    "account.full_name": "Nombre completo",
    "account.full_name_placeholder": "Tu nombre",
    "account.phone": "Celular",
    "account.phone_placeholder": "+57 300 000 0000",
    "account.save": "Guardar cambios",
    "account.saving": "Guardando...",
    "account.save_success": "Perfil actualizado correctamente",
    "account.save_error": "Error al guardar los cambios",
    "account.avatar": "Foto de perfil",
    "account.avatar_description": "Sube una imagen para tu perfil",
    "account.upload_photo": "Subir foto",
    "account.remove_photo": "Eliminar foto",
    "account.change_password": "Cambiar contraseña",
    "account.new_password": "Nueva contraseña",
    "account.confirm_password": "Confirmar contraseña",
    "account.password_min": "Mínimo 6 caracteres",
    "account.password_updated": "Contraseña actualizada correctamente",
    "account.password_error": "Error al cambiar la contraseña",
    "account.passwords_no_match": "Las contraseñas no coinciden",
    "account.danger_zone": "Zona de peligro",
    "account.danger_description": "Acciones irreversibles sobre tu cuenta.",
    "account.delete_account": "Eliminar cuenta",

    // Settings page
    "settings.title": "Configuración",
    "settings.subtitle": "Personaliza la aplicación a tu gusto",
    "settings.appearance": "Apariencia",
    "settings.appearance_description": "Elige el tema visual de la aplicación",
    "settings.theme_dark": "Oscuro",
    "settings.theme_dark_description": "Ideal para ambientes con poca luz",
    "settings.theme_light": "Claro",
    "settings.theme_light_description": "Ideal para ambientes iluminados",
    "settings.language": "Idioma",
    "settings.language_description": "Selecciona el idioma de la interfaz",
    "settings.lang_es": "Español",
    "settings.lang_es_description": "Interfaz en español",
    "settings.lang_en": "English",
    "settings.lang_en_description": "Interface in English",
    "settings.org_profile": "Perfil de organización",
    "settings.org_profile_description": "Información de tu clínica o negocio",
    "settings.org_name": "Nombre",
    "settings.org_name_placeholder": "Mi Clínica",
    "settings.org_slug": "Slug (URL)",
    "settings.org_slug_placeholder": "mi-clinica",
    "settings.org_logo": "Logo",
    "settings.org_upload_logo": "Subir logo",
    "settings.org_remove_logo": "Eliminar logo",
    "settings.org_save": "Guardar organización",
    "settings.org_saving": "Guardando...",
    "settings.org_save_success": "Organización actualizada",
    "settings.org_save_error": "Error al guardar la organización",
    "settings.org_admin_only": "Solo administradores pueden editar",
    "settings.org_slug_taken": "Ese slug ya está en uso. Elige otro.",
    "settings.access_denied": "No tienes permisos para acceder a esta sección",
    "settings.access_denied_description": "Solo los administradores pueden acceder a la configuración. Contacta al administrador de tu organización si necesitas realizar cambios.",

    // Validation
    "validation.name_min": "El nombre debe tener al menos 2 caracteres",
    "validation.name_max": "El nombre no puede superar 100 caracteres",
    "validation.phone_max": "El celular no puede superar 20 caracteres",

    // Dashboard
    "dashboard.welcome": "Bienvenido de vuelta",
    "dashboard.stats": "Estadísticas",
    "dashboard.total_patients": "Pacientes totales",
    "dashboard.today_appointments": "Citas de hoy",
    "dashboard.active_doctors": "Doctores activos",
    "dashboard.monthly_appointments": "Citas este mes",
    "dashboard.vs_last_month": "vs. mes anterior",
    "dashboard.today_schedule": "Agenda de hoy",
    "dashboard.upcoming_appointments": "Próximas 3 citas",
    "dashboard.view_scheduler": "Ver agenda completa",
    "dashboard.no_appointments_today": "No hay citas programadas para hoy",
    "dashboard.no_upcoming_appointments": "No hay citas próximas",

    // Admin hub
    "admin.title": "Administración",
    "admin.subtitle": "Configura los parámetros del sistema",
    "admin.offices_card": "Consultorios",
    "admin.offices_desc": "Gestiona los espacios físicos",
    "admin.doctors_card": "Doctores",
    "admin.doctors_desc": "Gestiona el personal médico",
    "admin.services_card": "Catálogo de Servicios",
    "admin.services_desc": "Configura procedimientos y precios",
    "admin.lookups_card": "Variables Globales",
    "admin.lookups_desc": "Listas desplegables del sistema",

    // Offices
    "offices.title": "Consultorios",
    "offices.subtitle": "Gestiona los consultorios disponibles",
    "offices.name": "Nombre",
    "offices.description": "Descripción",
    "offices.active": "Activo",
    "offices.save_success": "Consultorio guardado",
    "offices.save_error": "Error al guardar el consultorio",
    "offices.add": "Agregar Consultorio",
    "offices.delete_confirm": "¿Eliminar este consultorio?",
    "offices.delete_success": "Consultorio eliminado",
    "offices.no_offices": "No hay consultorios registrados",

    // Doctors
    "doctors.title": "Doctores",
    "doctors.subtitle": "Gestiona el equipo médico",
    "doctors.add": "Agregar Doctor",
    "doctors.name": "Nombre completo",
    "doctors.cmp": "CMP (N° de colegiatura)",
    "doctors.photo": "Foto",
    "doctors.color": "Color identificador",
    "doctors.status": "Estado",
    "doctors.active": "Activo",
    "doctors.inactive": "Inactivo",
    "doctors.services_tab": "Servicios",
    "doctors.schedule_tab": "Horario",
    "doctors.profile_tab": "Perfil",
    "doctors.service_matrix": "Matriz de Servicios",
    "doctors.service_matrix_desc": "Selecciona los procedimientos que realiza este doctor",
    "doctors.schedule_title": "Horario Semanal",
    "doctors.schedule_desc": "Define la disponibilidad semanal del doctor",
    "doctors.save_success": "Doctor guardado correctamente",
    "doctors.save_error": "Error al guardar el doctor",
    "doctors.delete_confirm": "¿Eliminar este doctor?",
    "doctors.delete_success": "Doctor eliminado",
    "doctors.no_doctors": "No hay doctores registrados",
    "doctors.edit": "Editar Doctor",

    // Services
    "services.title": "Catálogo de Servicios",
    "services.subtitle": "Configura los procedimientos disponibles",
    "services.add": "Agregar Servicio",
    "services.name": "Nombre del servicio",
    "services.category": "Categoría",
    "services.base_price": "Precio base",
    "services.duration": "Duración (min)",
    "services.active": "Activo",
    "services.save_success": "Servicio guardado correctamente",
    "services.save_error": "Error al guardar el servicio",
    "services.delete_confirm": "¿Eliminar este servicio?",
    "services.delete_success": "Servicio eliminado",
    "services.no_services": "No hay servicios registrados",
    "services.categories": "Categorías",
    "services.add_category": "Agregar Categoría",
    "services.category_name": "Nombre de categoría",
    "services.category_save_success": "Categoría guardada",
    "services.category_delete_success": "Categoría eliminada",
    "services.category_delete_confirm": "¿Eliminar esta categoría?",

    // Lookups
    "lookups.title": "Variables Globales",
    "lookups.subtitle": "Administra las listas desplegables del sistema",
    "lookups.tab_origins": "Orígenes",
    "lookups.tab_payment_methods": "Métodos de Pago",
    "lookups.tab_appointment_status": "Estados de Cita",
    "lookups.tab_responsible": "Responsables",
    "lookups.add_value": "Agregar",
    "lookups.label": "Etiqueta",
    "lookups.value": "Valor",
    "lookups.color": "Color",
    "lookups.order": "Orden",
    "lookups.save_success": "Valor guardado",
    "lookups.save_error": "Error al guardar",
    "lookups.delete_success": "Valor eliminado",
    "lookups.delete_confirm": "¿Eliminar este valor?",

    // Schedule (admin)
    "schedule.start_time": "Hora inicio",
    "schedule.end_time": "Hora fin",
    "schedule.office": "Consultorio",
    "schedule.add_block": "Agregar bloque",
    "schedule.remove_block": "Eliminar",

    // Scheduler history
    "nav.scheduler_calendar": "Agenda",
    "nav.scheduler_history": "Histórico de citas",
    "history.title": "Histórico de Citas",
    "history.subtitle": "Registro cronológico de todas las citas",
    "history.filters": "Filtros",
    "history.date_from": "Desde",
    "history.date_to": "Hasta",
    "history.records": "registros",
    "history.price": "Precio",
    "history.price_locked": "Precio bloqueado al momento de la cita",

    // Scheduler (module 2)
    "scheduler.editing": "Editando",
    "scheduler.edited_label": "editó:",
    "scheduler.title": "Agenda",
    "scheduler.today": "Hoy",
    "scheduler.day_view": "Día",
    "scheduler.week_view": "Semana",
    "scheduler.new_appointment": "Nueva Cita",
    "scheduler.patient_name": "Nombre del paciente",
    "scheduler.patient_phone": "Teléfono",
    "scheduler.doctor": "Doctor",
    "scheduler.office": "Consultorio",
    "scheduler.service": "Servicio",
    "scheduler.date": "Fecha",
    "scheduler.time": "Hora",
    "scheduler.status": "Estado",
    "scheduler.origin": "Origen",
    "scheduler.payment_method": "Método de pago",
    "scheduler.responsible": "Responsable",
    "scheduler.notes": "Notas",
    "scheduler.save_success": "Cita guardada correctamente",
    "scheduler.save_error": "Error al guardar la cita",
    "scheduler.delete_confirm": "¿Eliminar esta cita?",
    "scheduler.delete_success": "Cita eliminada",
    "scheduler.conflict_error": "Conflicto: ya existe una cita en ese horario y consultorio",
    "scheduler.conflict_doctor": "Alerta: el doctor ya tiene una cita a esa hora en otro consultorio",
    "scheduler.status_scheduled": "Programada",
    "scheduler.status_confirmed": "Confirmada",
    "scheduler.status_completed": "Completada",
    "scheduler.status_cancelled": "Cancelada",
    "scheduler.status_no_show": "No asistió",
    "scheduler.overview_total": "Total citas",
    "scheduler.overview_pending": "Pendientes",
    "scheduler.overview_occupation": "Ocupación",
    "scheduler.empty_slot": "Disponible",
    "scheduler.details": "Detalles de la cita",
    "scheduler.confirm": "Confirmar",
    "scheduler.complete": "Completar",
    "scheduler.cancel_appointment": "Cancelar cita",

    // Patients (module 3)
    "nav.patients": "Pacientes",
    "patients.title": "Lista Maestra",
    "patients.subtitle": "Directorio de pacientes",
    "patients.add": "Nuevo Paciente",
    "patients.search_placeholder": "Buscar por nombre, DNI o celular...",
    "patients.dni": "DNI",
    "patients.first_name": "Nombres",
    "patients.last_name": "Apellidos",
    "patients.phone": "Celular",
    "patients.email": "Email",
    "patients.status": "Estado",
    "patients.active": "Activo",
    "patients.inactive": "Inactivo",
    "patients.origin": "Origen",
    "patients.tags": "Etiquetas",
    "patients.add_tag": "Agregar etiqueta",
    "patients.notes": "Notas",
    "patients.profile": "Perfil 360°",
    "patients.tab_history": "Historial",
    "patients.tab_finances": "Finanzas",
    "patients.tab_marketing": "Marketing",
    "patients.history_empty": "Sin citas registradas",
    "patients.attended": "Asistió",
    "patients.cancelled": "Canceló",
    "patients.no_show": "No asistió",
    "patients.total_debt": "Deuda total",
    "patients.total_paid": "Total pagado",
    "patients.pending_balance": "Saldo pendiente",
    "patients.add_payment": "Registrar pago",
    "patients.payment_amount": "Monto",
    "patients.payment_date": "Fecha de pago",
    "patients.payment_method": "Método de pago",
    "patients.adicional_1": "Adicional 1",
    "patients.adicional_2": "Adicional 2",
    "patients.viene_desde": "Viene desde",
    "patients.save_success": "Paciente guardado correctamente",
    "patients.save_error": "Error al guardar el paciente",
    "patients.delete_confirm": "¿Eliminar este paciente?",
    "patients.delete_success": "Paciente eliminado",
    "patients.payment_save_success": "Pago registrado",
    "patients.payment_save_error": "Error al registrar el pago",
    "patients.no_patients": "No hay pacientes registrados",
    "patients.filter_all": "Todos",
    "patients.filter_active": "Activos",
    "patients.filter_inactive": "Inactivos",
    "patients.patient_found": "Paciente encontrado",
    "patients.patient_new": "Nuevo paciente (se creará automáticamente)",
    "patients.service_price": "Precio servicio",
    "patients.amount_paid": "Monto pagado",
    "patients.filters": "Filtros",
    "patients.filter_clear": "Limpiar",
    "patients.filter_tags": "Etiquetas",
    "patients.filter_tags_placeholder": "Seleccionar etiquetas...",
    "patients.filter_service": "Servicio",
    "patients.filter_service_placeholder": "Todos los servicios",
    "patients.filter_date_from": "Registrado desde",
    "patients.filter_date_to": "Registrado hasta",
    "patients.filter_with_debt": "Con saldo pendiente",
    "patients.filter_origin": "Viene desde",
    "patients.filter_origin_placeholder": "Todos los orígenes",
    "scheduler.patient_dni": "DNI del paciente",
    "scheduler.search_patient": "Buscar paciente por DNI",

    // Reports (module 4)
    "nav.reports": "Reportes",
    "reports.title": "Reportes",
    "reports.subtitle": "Inteligencia de negocio y KPIs",
    "reports.tab_financial": "Financiero",
    "reports.tab_marketing": "Marketing",
    "reports.tab_operational": "Operacional",
    "reports.preset_today": "Hoy",
    "reports.preset_7d": "7d",
    "reports.preset_30d": "30d",
    "reports.preset_90d": "90d",
    "reports.preset_this_month": "Este mes",
    "reports.total_billed": "Total facturado",
    "reports.total_collected": "Total cobrado",
    "reports.total_attended": "Atendidos",
    "reports.total_cancelled": "Cancelados",
    "reports.appointments_by_doctor": "Citas por doctor",
    "reports.revenue_by_doctor": "Facturación por doctor",
    "reports.doctor_productivity": "Productividad por doctor",
    "reports.export_csv": "Exportar CSV",
    "reports.doctor": "Doctor",
    "reports.total": "Total",
    "reports.attended": "Atendidos",
    "reports.confirmed": "Confirmados",
    "reports.scheduled": "Programados",
    "reports.cancelled": "Cancelados",
    "reports.billed": "Facturado",
    "reports.avg_per_appointment": "Prom./Cita",
    "reports.conversion_rate": "Tasa de conversión",
    "reports.cancel_rate": "Tasa de cancelación",
    "reports.unique_origins": "Orígenes únicos",
    "reports.total_patients": "Total pacientes",
    "reports.origin_distribution": "Distribución por origen",
    "reports.conversion_by_origin": "Conversión por origen",
    "reports.origin": "Origen",
    "reports.avg_daily": "Prom. diario",
    "reports.appointments_per_day": "citas/día",
    "reports.peak_hour": "Hora pico",
    "reports.appointments": "citas",
    "reports.top_service": "Servicio top",
    "reports.offices_used": "Consultorios",
    "reports.daily_trend": "Tendencia diaria",
    "reports.peak_hours": "Horas pico",
    "reports.top_services": "Top servicios",
    "reports.office_occupancy": "Ocupación por consultorio",
    "reports.service": "Servicio",
    "reports.count": "Citas",
    "reports.revenue": "Facturado",
    "reports.total_no_shows": "No-Shows",
    "reports.tooltip_total_billed": "Suma del precio de todas las citas atendidas y confirmadas",
    "reports.total_pending": "Pendiente cobro",
    "reports.tooltip_total_pending": "Diferencia entre lo facturado y lo efectivamente cobrado",
    "reports.tooltip_total_collected": "Total de pagos registrados en el periodo",
    "reports.tooltip_total_attended": "Citas marcadas como completadas/atendidas",
    "reports.tooltip_total_cancelled": "Citas canceladas en el periodo seleccionado",
    "reports.tooltip_no_shows": "Citas pasadas que nunca fueron marcadas como completadas",
    "reports.tooltip_conversion_rate": "Porcentaje de citas agendadas que fueron atendidas",
    "reports.tooltip_cancel_rate": "Porcentaje de citas que fueron canceladas",
    "reports.tooltip_unique_origins": "Cantidad de canales de origen distintos registrados",
    "reports.tooltip_total_patients": "Pacientes registrados en el periodo seleccionado",
    "reports.tooltip_avg_daily": "Promedio de citas activas por día en el periodo",
    "reports.tooltip_peak_hour": "Hora del día con mayor cantidad de citas",
    "reports.tooltip_top_service": "Servicio con más citas agendadas en el periodo",
    "reports.tooltip_offices_used": "Cantidad de consultorios utilizados en el periodo",

    // Members
    "members.title": "Miembros",
    "members.subtitle": "Gestiona los usuarios de tu organización",
    "members.invite": "Invitar miembro",
    "members.invite_title": "Invitar miembro",
    "members.invite_description": "Ingresa el correo electrónico. Si no tiene cuenta, recibirá un email para registrarse.",
    "members.email": "Correo electrónico",
    "members.email_placeholder": "usuario@ejemplo.com",
    "members.role": "Rol",
    "members.role_owner": "Propietario",
    "members.role_admin": "Administrador",
    "members.role_member": "Miembro",
    "members.role_receptionist": "Recepcionista",
    "members.role_admin_desc": "Acceso total al panel",
    "members.role_member_desc": "Agenda y pacientes",
    "members.role_receptionist_desc": "Agenda y pacientes",
    "members.title_doctor": "Doctor/a",
    "members.title_doctor_desc": "Profesional médico",
    "members.title_especialista": "Especialista",
    "members.title_especialista_desc": "Profesional especializado",
    "members.title_licenciada": "Licenciado/a",
    "members.title_licenciada_desc": "Profesional licenciado",
    "members.admin_extra_cost": "*Habilitar otro administrador conlleva un coste adicional.",
    "members.contact_support": "Contactar a soporte",
    "members.inviting": "Invitando...",
    "members.invite_success": "Miembro agregado exitosamente",
    "members.invitation_sent": "Invitación enviada. El usuario recibirá un email para registrarse.",
    "members.invitation_created_no_email": "Invitación creada, pero no se pudo enviar el correo. Comparte este enlace de registro manualmente:",
    "members.invite_error": "Error al enviar la invitación",
    "members.already_invited": "Ya se envió una invitación pendiente a este correo",
    "members.already_member": "Este usuario ya es miembro de tu organización",
    "members.role_change_success": "Rol actualizado",
    "members.role_change_error": "Error al cambiar el rol",
    "members.remove_confirm": "¿Eliminar este miembro de la organización?",
    "members.remove_success": "Miembro eliminado",
    "members.remove_error": "Error al eliminar miembro",
    "members.total_members": "miembros",
    "members.no_members": "No hay miembros registrados",
    "members.unnamed": "Sin nombre",
    "admin.members_card": "Miembros",
    "admin.members_desc": "Gestiona los usuarios de la organización",

    // Email settings
    "email.general_title": "Configuración general",
    "email.general_description": "Datos del remitente y branding para todos los correos",
    "email.sender_name": "Nombre del remitente",
    "email.sender_name_placeholder": "Clínica San Marcos",
    "email.sender_email": "Email del remitente",
    "email.sender_email_placeholder": "no-reply@tuclinica.com",
    "email.reply_to": "Email de respuesta (reply-to)",
    "email.reply_to_placeholder": "contacto@tuclinica.com",
    "email.brand_color": "Color principal",
    "email.email_logo": "Logo para correos",
    "email.upload_logo": "Subir logo",
    "email.remove_logo": "Eliminar",
    "email.use_org_logo": "Usar logo de la organización",
    "email.save_settings": "Guardar configuración",
    "email.save_settings_saving": "Guardando...",
    "email.save_settings_success": "Configuración de correo guardada",
    "email.save_settings_error": "Error al guardar la configuración",
    "email.invalid_sender_email": "El correo del remitente no es válido",
    "email.invalid_reply_to_email": "El correo de respuesta no es válido",
    "email.templates_title": "Plantillas de correo",
    "email.templates_description": "Configura el contenido y comportamiento de cada notificación",
    "email.cat_appointments": "Citas",
    "email.cat_patients": "Pacientes",
    "email.cat_payments": "Pagos",
    "email.cat_team": "Equipo interno",
    "email.cat_marketing": "Marketing",
    "email.enabled": "Activo",
    "email.disabled": "Inactivo",
    "email.edit_template": "Editar plantilla",
    "email.send_test": "Enviar prueba",
    "email.test_sent": "Correo de prueba enviado",
    "email.test_error": "Error al enviar correo de prueba",
    "email.channel": "Canal",
    "email.channel_email": "Email",
    "email.channel_whatsapp": "WhatsApp",
    "email.channel_both": "Ambos",
    "email.timing": "Cuándo se envía",
    "email.timing_before": "antes",
    "email.timing_minutes": "minutos",
    "email.timing_hours": "horas",
    "email.timing_days": "días",
    "email.subject": "Asunto",
    "email.body": "Cuerpo del mensaje",
    "email.variables": "Variables disponibles",
    "email.variable_hint": "Haz clic en una variable para insertarla",
    "email.preview": "Vista previa",
    "email.save_template": "Guardar plantilla",
    "email.save_template_saving": "Guardando...",
    "email.save_template_success": "Plantilla guardada",
    "email.save_template_error": "Error al guardar la plantilla",
    "email.locked_plan": "Disponible en Plan",
    "email.upgrade_hint": "Mejora tu plan para desbloquear esta plantilla",
    "email.no_timing": "Inmediato / Manual",
    "email.back_to_list": "Volver a plantillas",

    // Common
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.add": "Agregar",
    "common.search": "Buscar...",
    "common.actions": "Acciones",
    "common.active": "Activo",
    "common.inactive": "Inactivo",
    "common.confirm_delete": "Confirmar eliminación",
    "common.confirm_delete_desc": "Esta acción no se puede deshacer.",
    "common.no_results": "Sin resultados",
    "common.loading": "Cargando...",
    "common.back": "Volver",
    "common.minutes_short": "min",
    "common.currency_symbol": "S/.",
  },
  en: {
    // Sidebar
    "nav.dashboard": "Dashboard",
    "nav.account": "Account",
    "nav.settings": "Settings",
    "nav.logout": "Log out",
    "nav.logout_success": "Logged out",
    "nav.scheduler": "Schedule",
    "nav.admin": "Administration",
    "nav.admin_offices": "Offices",
    "nav.admin_doctors": "Doctors",
    "nav.admin_services": "Services",
    "nav.admin_lookups": "Variables",
    "nav.admin_variables": "Global Variables",
    "nav.admin_members": "Members",
    "nav.founder": "Founder",

    // Account page
    "account.title": "My Account",
    "account.subtitle": "Manage your personal information",
    "account.personal_data": "Personal data",
    "account.full_name": "Full name",
    "account.full_name_placeholder": "Your name",
    "account.phone": "Phone",
    "account.phone_placeholder": "+1 555 000 0000",
    "account.save": "Save changes",
    "account.saving": "Saving...",
    "account.save_success": "Profile updated successfully",
    "account.save_error": "Error saving changes",
    "account.avatar": "Profile photo",
    "account.avatar_description": "Upload an image for your profile",
    "account.upload_photo": "Upload photo",
    "account.remove_photo": "Remove photo",
    "account.change_password": "Change password",
    "account.new_password": "New password",
    "account.confirm_password": "Confirm password",
    "account.password_min": "Minimum 6 characters",
    "account.password_updated": "Password updated successfully",
    "account.password_error": "Error changing password",
    "account.passwords_no_match": "Passwords do not match",
    "account.danger_zone": "Danger zone",
    "account.danger_description": "Irreversible actions on your account.",
    "account.delete_account": "Delete account",

    // Settings page
    "settings.title": "Settings",
    "settings.subtitle": "Customize the app to your liking",
    "settings.appearance": "Appearance",
    "settings.appearance_description": "Choose the visual theme of the app",
    "settings.theme_dark": "Dark",
    "settings.theme_dark_description": "Ideal for low-light environments",
    "settings.theme_light": "Light",
    "settings.theme_light_description": "Ideal for bright environments",
    "settings.language": "Language",
    "settings.language_description": "Select the interface language",
    "settings.lang_es": "Español",
    "settings.lang_es_description": "Interfaz en español",
    "settings.lang_en": "English",
    "settings.lang_en_description": "Interface in English",
    "settings.org_profile": "Organization profile",
    "settings.org_profile_description": "Your clinic or business information",
    "settings.org_name": "Name",
    "settings.org_name_placeholder": "My Clinic",
    "settings.org_slug": "Slug (URL)",
    "settings.org_slug_placeholder": "my-clinic",
    "settings.org_logo": "Logo",
    "settings.org_upload_logo": "Upload logo",
    "settings.org_remove_logo": "Remove logo",
    "settings.org_save": "Save organization",
    "settings.org_saving": "Saving...",
    "settings.org_save_success": "Organization updated",
    "settings.org_save_error": "Error saving organization",
    "settings.org_admin_only": "Only admins can edit",
    "settings.org_slug_taken": "That slug is already in use. Please choose another.",
    "settings.access_denied": "You don't have permission to access this section",
    "settings.access_denied_description": "Only administrators can access settings. Contact your organization administrator if you need to make changes.",

    // Validation
    "validation.name_min": "Name must be at least 2 characters",
    "validation.name_max": "Name cannot exceed 100 characters",
    "validation.phone_max": "Phone cannot exceed 20 characters",

    // Dashboard
    "dashboard.welcome": "Welcome back",
    "dashboard.stats": "Statistics",
    "dashboard.total_patients": "Total patients",
    "dashboard.today_appointments": "Today's appointments",
    "dashboard.active_doctors": "Active doctors",
    "dashboard.monthly_appointments": "This month",
    "dashboard.vs_last_month": "vs. last month",
    "dashboard.today_schedule": "Today's schedule",
    "dashboard.upcoming_appointments": "Next 3 appointments",
    "dashboard.view_scheduler": "View full schedule",
    "dashboard.no_appointments_today": "No appointments scheduled for today",
    "dashboard.no_upcoming_appointments": "No upcoming appointments",

    // Admin hub
    "admin.title": "Administration",
    "admin.subtitle": "Configure system parameters",
    "admin.offices_card": "Offices",
    "admin.offices_desc": "Manage physical spaces",
    "admin.doctors_card": "Doctors",
    "admin.doctors_desc": "Manage medical staff",
    "admin.services_card": "Service Catalog",
    "admin.services_desc": "Configure procedures and pricing",
    "admin.lookups_card": "Global Variables",
    "admin.lookups_desc": "System dropdown lists",

    // Offices
    "offices.title": "Offices",
    "offices.subtitle": "Manage available offices",
    "offices.name": "Name",
    "offices.description": "Description",
    "offices.active": "Active",
    "offices.save_success": "Office saved",
    "offices.save_error": "Error saving office",
    "offices.add": "Add Office",
    "offices.delete_confirm": "Delete this office?",
    "offices.delete_success": "Office deleted",
    "offices.no_offices": "No offices registered",

    // Doctors
    "doctors.title": "Doctors",
    "doctors.subtitle": "Manage the medical team",
    "doctors.add": "Add Doctor",
    "doctors.name": "Full name",
    "doctors.cmp": "CMP (License number)",
    "doctors.photo": "Photo",
    "doctors.color": "Identifier color",
    "doctors.status": "Status",
    "doctors.active": "Active",
    "doctors.inactive": "Inactive",
    "doctors.services_tab": "Services",
    "doctors.schedule_tab": "Schedule",
    "doctors.profile_tab": "Profile",
    "doctors.service_matrix": "Service Matrix",
    "doctors.service_matrix_desc": "Select procedures this doctor performs",
    "doctors.schedule_title": "Weekly Schedule",
    "doctors.schedule_desc": "Define the doctor's weekly availability",
    "doctors.save_success": "Doctor saved successfully",
    "doctors.save_error": "Error saving doctor",
    "doctors.delete_confirm": "Delete this doctor?",
    "doctors.delete_success": "Doctor deleted",
    "doctors.no_doctors": "No doctors registered",
    "doctors.edit": "Edit Doctor",

    // Services
    "services.title": "Service Catalog",
    "services.subtitle": "Configure available procedures",
    "services.add": "Add Service",
    "services.name": "Service name",
    "services.category": "Category",
    "services.base_price": "Base price",
    "services.duration": "Duration (min)",
    "services.active": "Active",
    "services.save_success": "Service saved successfully",
    "services.save_error": "Error saving service",
    "services.delete_confirm": "Delete this service?",
    "services.delete_success": "Service deleted",
    "services.no_services": "No services registered",
    "services.categories": "Categories",
    "services.add_category": "Add Category",
    "services.category_name": "Category name",
    "services.category_save_success": "Category saved",
    "services.category_delete_success": "Category deleted",
    "services.category_delete_confirm": "Delete this category?",

    // Lookups
    "lookups.title": "Global Variables",
    "lookups.subtitle": "Manage system dropdown lists",
    "lookups.tab_origins": "Origins",
    "lookups.tab_payment_methods": "Payment Methods",
    "lookups.tab_appointment_status": "Appointment Status",
    "lookups.tab_responsible": "Responsible",
    "lookups.add_value": "Add",
    "lookups.label": "Label",
    "lookups.value": "Value",
    "lookups.color": "Color",
    "lookups.order": "Order",
    "lookups.save_success": "Value saved",
    "lookups.save_error": "Error saving",
    "lookups.delete_success": "Value deleted",
    "lookups.delete_confirm": "Delete this value?",

    // Schedule (admin)
    "schedule.start_time": "Start time",
    "schedule.end_time": "End time",
    "schedule.office": "Office",
    "schedule.add_block": "Add block",
    "schedule.remove_block": "Remove",

    // Scheduler history
    "nav.scheduler_calendar": "Schedule",
    "nav.scheduler_history": "Appointment History",
    "history.title": "Appointment History",
    "history.subtitle": "Chronological record of all appointments",
    "history.filters": "Filters",
    "history.date_from": "From",
    "history.date_to": "To",
    "history.records": "records",
    "history.price": "Price",
    "history.price_locked": "Price locked at appointment time",

    // Scheduler (module 2)
    "scheduler.editing": "Editing",
    "scheduler.edited_label": "edited:",
    "scheduler.title": "Schedule",
    "scheduler.today": "Today",
    "scheduler.day_view": "Day",
    "scheduler.week_view": "Week",
    "scheduler.new_appointment": "New Appointment",
    "scheduler.patient_name": "Patient name",
    "scheduler.patient_phone": "Phone",
    "scheduler.doctor": "Doctor",
    "scheduler.office": "Office",
    "scheduler.service": "Service",
    "scheduler.date": "Date",
    "scheduler.time": "Time",
    "scheduler.status": "Status",
    "scheduler.origin": "Origin",
    "scheduler.payment_method": "Payment method",
    "scheduler.responsible": "Responsible",
    "scheduler.notes": "Notes",
    "scheduler.save_success": "Appointment saved successfully",
    "scheduler.save_error": "Error saving appointment",
    "scheduler.delete_confirm": "Delete this appointment?",
    "scheduler.delete_success": "Appointment deleted",
    "scheduler.conflict_error": "Conflict: an appointment already exists at that time and office",
    "scheduler.conflict_doctor": "Warning: the doctor already has an appointment at that time in another office",
    "scheduler.status_scheduled": "Scheduled",
    "scheduler.status_confirmed": "Confirmed",
    "scheduler.status_completed": "Completed",
    "scheduler.status_cancelled": "Cancelled",
    "scheduler.status_no_show": "No show",
    "scheduler.overview_total": "Total appointments",
    "scheduler.overview_pending": "Pending",
    "scheduler.overview_occupation": "Occupation",
    "scheduler.empty_slot": "Available",
    "scheduler.details": "Appointment details",
    "scheduler.confirm": "Confirm",
    "scheduler.complete": "Complete",
    "scheduler.cancel_appointment": "Cancel appointment",

    // Patients (module 3)
    "nav.patients": "Patients",
    "patients.title": "Master List",
    "patients.subtitle": "Patient directory",
    "patients.add": "New Patient",
    "patients.search_placeholder": "Search by name, ID or phone...",
    "patients.dni": "ID Number",
    "patients.first_name": "First name",
    "patients.last_name": "Last name",
    "patients.phone": "Phone",
    "patients.email": "Email",
    "patients.status": "Status",
    "patients.active": "Active",
    "patients.inactive": "Inactive",
    "patients.origin": "Origin",
    "patients.tags": "Tags",
    "patients.add_tag": "Add tag",
    "patients.notes": "Notes",
    "patients.profile": "360° Profile",
    "patients.tab_history": "History",
    "patients.tab_finances": "Finances",
    "patients.tab_marketing": "Marketing",
    "patients.history_empty": "No appointments recorded",
    "patients.attended": "Attended",
    "patients.cancelled": "Cancelled",
    "patients.no_show": "No show",
    "patients.total_debt": "Total debt",
    "patients.total_paid": "Total paid",
    "patients.pending_balance": "Pending balance",
    "patients.add_payment": "Record payment",
    "patients.payment_amount": "Amount",
    "patients.payment_date": "Payment date",
    "patients.payment_method": "Payment method",
    "patients.adicional_1": "Additional 1",
    "patients.adicional_2": "Additional 2",
    "patients.viene_desde": "Referred from",
    "patients.save_success": "Patient saved successfully",
    "patients.save_error": "Error saving patient",
    "patients.delete_confirm": "Delete this patient?",
    "patients.delete_success": "Patient deleted",
    "patients.payment_save_success": "Payment recorded",
    "patients.payment_save_error": "Error recording payment",
    "patients.no_patients": "No patients registered",
    "patients.filter_all": "All",
    "patients.filter_active": "Active",
    "patients.filter_inactive": "Inactive",
    "patients.patient_found": "Patient found",
    "patients.patient_new": "New patient (will be created automatically)",
    "patients.service_price": "Service price",
    "patients.amount_paid": "Amount paid",
    "patients.filters": "Filters",
    "patients.filter_clear": "Clear",
    "patients.filter_tags": "Tags",
    "patients.filter_tags_placeholder": "Select tags...",
    "patients.filter_service": "Service",
    "patients.filter_service_placeholder": "All services",
    "patients.filter_date_from": "Registered from",
    "patients.filter_date_to": "Registered to",
    "patients.filter_with_debt": "With pending balance",
    "patients.filter_origin": "Referred from",
    "patients.filter_origin_placeholder": "All origins",
    "scheduler.patient_dni": "Patient ID",
    "scheduler.search_patient": "Search patient by ID",

    // Reports (module 4)
    "nav.reports": "Reports",
    "reports.title": "Reports",
    "reports.subtitle": "Business intelligence & KPIs",
    "reports.tab_financial": "Financial",
    "reports.tab_marketing": "Marketing",
    "reports.tab_operational": "Operational",
    "reports.preset_today": "Today",
    "reports.preset_7d": "7d",
    "reports.preset_30d": "30d",
    "reports.preset_90d": "90d",
    "reports.preset_this_month": "This month",
    "reports.total_billed": "Total billed",
    "reports.total_collected": "Total collected",
    "reports.total_attended": "Attended",
    "reports.total_cancelled": "Cancelled",
    "reports.appointments_by_doctor": "Appointments by doctor",
    "reports.revenue_by_doctor": "Revenue by doctor",
    "reports.doctor_productivity": "Doctor productivity",
    "reports.export_csv": "Export CSV",
    "reports.doctor": "Doctor",
    "reports.total": "Total",
    "reports.attended": "Attended",
    "reports.confirmed": "Confirmed",
    "reports.scheduled": "Scheduled",
    "reports.cancelled": "Cancelled",
    "reports.billed": "Billed",
    "reports.avg_per_appointment": "Avg/Appt",
    "reports.conversion_rate": "Conversion rate",
    "reports.cancel_rate": "Cancellation rate",
    "reports.unique_origins": "Unique origins",
    "reports.total_patients": "Total patients",
    "reports.origin_distribution": "Origin distribution",
    "reports.conversion_by_origin": "Conversion by origin",
    "reports.origin": "Origin",
    "reports.avg_daily": "Daily avg",
    "reports.appointments_per_day": "appts/day",
    "reports.peak_hour": "Peak hour",
    "reports.appointments": "appts",
    "reports.top_service": "Top service",
    "reports.offices_used": "Offices",
    "reports.daily_trend": "Daily trend",
    "reports.peak_hours": "Peak hours",
    "reports.top_services": "Top services",
    "reports.office_occupancy": "Office occupancy",
    "reports.service": "Service",
    "reports.count": "Appts",
    "reports.revenue": "Revenue",
    "reports.total_no_shows": "No-Shows",
    "reports.tooltip_total_billed": "Sum of prices for all attended and confirmed appointments",
    "reports.total_pending": "Pending",
    "reports.tooltip_total_pending": "Difference between billed and collected amounts",
    "reports.tooltip_total_collected": "Total registered payments in the period",
    "reports.tooltip_total_attended": "Appointments marked as completed/attended",
    "reports.tooltip_total_cancelled": "Appointments cancelled in the selected period",
    "reports.tooltip_no_shows": "Past appointments that were never marked as completed",
    "reports.tooltip_conversion_rate": "Percentage of scheduled appointments that were attended",
    "reports.tooltip_cancel_rate": "Percentage of appointments that were cancelled",
    "reports.tooltip_unique_origins": "Number of distinct origin channels registered",
    "reports.tooltip_total_patients": "Patients registered in the selected period",
    "reports.tooltip_avg_daily": "Average active appointments per day in the period",
    "reports.tooltip_peak_hour": "Time of day with the most appointments",
    "reports.tooltip_top_service": "Service with the most appointments in the period",
    "reports.tooltip_offices_used": "Number of offices used in the period",

    // Members
    "members.title": "Members",
    "members.subtitle": "Manage your organization's users",
    "members.invite": "Invite member",
    "members.invite_title": "Invite member",
    "members.invite_description": "Enter the email address. If they don't have an account, they'll receive an email to register.",
    "members.email": "Email",
    "members.email_placeholder": "user@example.com",
    "members.role": "Role",
    "members.role_owner": "Owner",
    "members.role_admin": "Admin",
    "members.role_member": "Member",
    "members.role_receptionist": "Receptionist",
    "members.role_admin_desc": "Full admin access",
    "members.role_member_desc": "Schedule & patients",
    "members.role_receptionist_desc": "Schedule & patients",
    "members.title_doctor": "Doctor",
    "members.title_doctor_desc": "Medical professional",
    "members.title_especialista": "Specialist",
    "members.title_especialista_desc": "Specialized professional",
    "members.title_licenciada": "Licensed Professional",
    "members.title_licenciada_desc": "Licensed professional",
    "members.admin_extra_cost": "*Enabling another administrator carries an additional cost.",
    "members.contact_support": "Contact support",
    "members.inviting": "Inviting...",
    "members.invite_success": "Member added successfully",
    "members.invitation_sent": "Invitation sent. The user will receive an email to register.",
    "members.invitation_created_no_email": "Invitation created, but the email could not be sent. Share this registration link manually:",
    "members.invite_error": "Error sending invitation",
    "members.already_invited": "An invitation has already been sent to this email",
    "members.already_member": "This user is already a member of your organization",
    "members.role_change_success": "Role updated",
    "members.role_change_error": "Error changing role",
    "members.remove_confirm": "Remove this member from the organization?",
    "members.remove_success": "Member removed",
    "members.remove_error": "Error removing member",
    "members.total_members": "members",
    "members.no_members": "No members registered",
    "members.unnamed": "Unnamed",
    "admin.members_card": "Members",
    "admin.members_desc": "Manage organization users",

    // Email settings
    "email.general_title": "General settings",
    "email.general_description": "Sender info and branding for all emails",
    "email.sender_name": "Sender name",
    "email.sender_name_placeholder": "My Clinic",
    "email.sender_email": "Sender email",
    "email.sender_email_placeholder": "no-reply@myclinic.com",
    "email.reply_to": "Reply-to email",
    "email.reply_to_placeholder": "contact@myclinic.com",
    "email.brand_color": "Brand color",
    "email.email_logo": "Email logo",
    "email.upload_logo": "Upload logo",
    "email.remove_logo": "Remove",
    "email.use_org_logo": "Use organization logo",
    "email.save_settings": "Save settings",
    "email.save_settings_saving": "Saving...",
    "email.save_settings_success": "Email settings saved",
    "email.save_settings_error": "Error saving email settings",
    "email.invalid_sender_email": "Sender email is not valid",
    "email.invalid_reply_to_email": "Reply-to email is not valid",
    "email.templates_title": "Email templates",
    "email.templates_description": "Configure the content and behavior of each notification",
    "email.cat_appointments": "Appointments",
    "email.cat_patients": "Patients",
    "email.cat_payments": "Payments",
    "email.cat_team": "Internal team",
    "email.cat_marketing": "Marketing",
    "email.enabled": "Active",
    "email.disabled": "Inactive",
    "email.edit_template": "Edit template",
    "email.send_test": "Send test",
    "email.test_sent": "Test email sent",
    "email.test_error": "Error sending test email",
    "email.channel": "Channel",
    "email.channel_email": "Email",
    "email.channel_whatsapp": "WhatsApp",
    "email.channel_both": "Both",
    "email.timing": "When to send",
    "email.timing_before": "before",
    "email.timing_minutes": "minutes",
    "email.timing_hours": "hours",
    "email.timing_days": "days",
    "email.subject": "Subject",
    "email.body": "Message body",
    "email.variables": "Available variables",
    "email.variable_hint": "Click a variable to insert it",
    "email.preview": "Preview",
    "email.save_template": "Save template",
    "email.save_template_saving": "Saving...",
    "email.save_template_success": "Template saved",
    "email.save_template_error": "Error saving template",
    "email.locked_plan": "Available on Plan",
    "email.upgrade_hint": "Upgrade your plan to unlock this template",
    "email.no_timing": "Immediate / Manual",
    "email.back_to_list": "Back to templates",

    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.add": "Add",
    "common.search": "Search...",
    "common.actions": "Actions",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.confirm_delete": "Confirm deletion",
    "common.confirm_delete_desc": "This action cannot be undone.",
    "common.no_results": "No results",
    "common.loading": "Loading...",
    "common.back": "Back",
    "common.minutes_short": "min",
    "common.currency_symbol": "$",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: "es",
  setLanguage: () => {},
  t: (key: string) => key,
});

export function useLanguage() {
  return useContext(LanguageContext);
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("es");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const saved = window.localStorage?.getItem("vibeforge-language") as Language;
    if (saved === "es" || saved === "en") {
      setLanguageState(saved);
    }
    setMounted(true);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      window.localStorage.setItem("vibeforge-language", lang);
    } catch {}
  };

  const t = (key: string): string => {
    return translations[language]?.[key] ?? key;
  };

  if (!mounted) {
    return <>{children}</>;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
