-- ============================================================================
-- Migration 114: ai_executive_briefs (Capa 1 - Reporte IA Avanzado)
-- ============================================================================
--
-- Stores executive summary briefs generated by the LLM (Capa 1 of the
-- "Reporte IA Avanzado" feature documented in COMING-UPDATES.md). Each row is
-- a single brief generated for a (organization, period) tuple.
--
-- Slice C scope (this migration): table + RLS only. Cron, weekly emails and
-- the historical page are deferred to later sessions. The first usage path is
-- a manual "Generate brief" button in the admin dashboard.
--
-- Notes:
--  * `period` is an enum-like text: 'week' | 'month' | 'custom'. We do not
--    use a real enum so future cadences (quarterly, year-to-date) don't
--    require ALTER TYPE.
--  * `metrics_snapshot` keeps the full RPC payload that fed the LLM, so we
--    can debug "why did the brief say X" weeks later without re-running the
--    metrics query.
--  * `llm_*` columns are for cost tracking and prompt iteration.
-- ============================================================================

CREATE TABLE IF NOT EXISTS ai_executive_briefs (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id   UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  generated_by      UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  period            TEXT NOT NULL CHECK (period IN ('week','month','custom')),
  period_start      DATE NOT NULL,
  period_end        DATE NOT NULL,
  content_markdown  TEXT NOT NULL,
  metrics_snapshot  JSONB NOT NULL,
  llm_model         TEXT NOT NULL,
  llm_tokens_input  INT,
  llm_tokens_output INT,
  generated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (period_end >= period_start)
);

CREATE INDEX IF NOT EXISTS idx_ai_executive_briefs_org_generated
  ON ai_executive_briefs(organization_id, generated_at DESC);

CREATE INDEX IF NOT EXISTS idx_ai_executive_briefs_org_period
  ON ai_executive_briefs(organization_id, period, period_start DESC);

ALTER TABLE ai_executive_briefs ENABLE ROW LEVEL SECURITY;

-- RLS: org members can read briefs of their org. Writes only happen
-- server-side via SECURITY DEFINER routes (the API endpoint), so we don't
-- need an INSERT policy for normal users.
DROP POLICY IF EXISTS "org_select_ai_executive_briefs" ON ai_executive_briefs;
CREATE POLICY "org_select_ai_executive_briefs" ON ai_executive_briefs FOR SELECT
  USING (organization_id IN (SELECT get_user_org_ids()));

-- Admins can delete briefs (e.g. clean up bad outputs during prompt
-- iteration). Owner role only — receptionists shouldn't touch this.
DROP POLICY IF EXISTS "org_delete_ai_executive_briefs" ON ai_executive_briefs;
CREATE POLICY "org_delete_ai_executive_briefs" ON ai_executive_briefs FOR DELETE
  USING (is_org_admin(organization_id));

COMMENT ON TABLE ai_executive_briefs IS
  'Executive summary briefs generated by LLM (Capa 1 - Reporte IA Avanzado). One row per (org, period) generation.';
